
Vagrant.require_version ">= 1.4.0"

Vagrant.configure("2") do |config|
  config.vm.box = "docker"

  config.vm.network "forwarded_port", guest: 8000, host: 8000,
    auto_correct: true

  config.vm.network "forwarded_port", guest: 44300, host: 44300,
    auto_correct: true

  config.vm.network "forwarded_port", guest: 22000, host: 22000,
    auto_correct: true

  config.vm.provider "virtualbox" do |v|
    v.name = "docker"
    v.memory = 1024
  end

end
